image: dtsdwarak/minideb-ruby-nodejs:ruby-3.3.4

pages:
  stage: deploy
  script:
  - npm install
  - npm install -g gulp-cli
  - bundle install
  - bundle update
  - gem install jekyll -v 4.3
  - gulp release
  artifacts:
    paths:
    - public
  only:
  - main
