image: dtsdwarak/minideb-ruby-nodejs:latest

pages:
  stage: deploy
  script:
  - npm install
  - npm install -g gulp-cli
  - bundle install
  - bundle update
  - gem install jekyll -v 3.8.7
  - gulp release
  artifacts:
    paths:
    - public
  only:
  - master
