# Jekyll configuration

name: Dwarak
description: Code. Life. Fun.

# url is currently only used only for the RSS feed in feed.xml
url: https://blog.dwarak.in

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ""
paginate: 3

highlighter: rouge
markdown: kramdown
plugins: ["jekyll-paginate"]

# Jekyll collections
# Documentation - https://jekyllrb.com/docs/collections/
collections_dir: collections
collections:
  books:
    output: true
    permalink: /:collection/:title/
  travel:
    output: true
    permalink: /:collection/:title/
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  finance:
    output: true
    permalink: /:collection/:title/

exclude:
  [
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
    "gulpfile.js",
    "css",
    "js",
    "images",
    "package-lock.json",
    "Gemfile.lock",
    "Gemfile",
  ]
